#!/bin/bash

# get filename from command line arguments
filename=$1

# read each line of the file
while read -r line; do
  n=$line
  # check if n is even
  if [ $((n%2)) -eq 0 ]; then
    # n is even, so 2 is a factor
    p=2
    q=$((n/2))
  else
    # n is odd, start checking odd factors starting from 3
    for i in $(seq 3 2 $((n/2))); do
      if [ $((n%i)) -eq 0 ]; then
        # found a factor, exit loop
        p=$i
        q=$((n/i))
        break
      fi
    done
    # if no factor was found, set p=n and q=1
    if [ -z "$p" ]; then
      p=$n
      q=1
    fi
  fi
  # print the factorization
  echo "${n}=${p}*${q}"
done < "$filename"

