#!/bin/bash
# get filename from command line arguments
filename=$1

# read each line of the file
while read line; do
  # assign the value of the line to the variable 'n'
  n=$line

  # set p and q to 1 initially
  p=1
  q=1

  # iterate through integers from 2 to n-1
  for ((i=2; i<n; i++)); do
    # check if i divides n evenly
    if [[ $((n % i)) -eq 0 ]]; then
      # if it does, set p and q to i and n/i respectively
      p=$i
      q=$((n / i))
      break
    fi
  done

  # print the factorization in the required format
  echo "$n=$p*$q"
done < "$filename"
